name: multi-sem
channels:
  - conda-forge
dependencies:
  - jax>=0.2.25
  - matplotlib
  - numpy==2.2.6
  - pip
  - python>=3.10
  - scikit-image>=0.17.2
  - pip:
    - connectomics
    - git+https://github.com/google-research/sofima
